---
# Super-Linter configuration for Symfony FrankenPHP project
# This file configures which linters to run and which files to ignore

# Disable all linters by default
VALIDATE_ALL_CODEBASE: false

# Enable only the linters we need
VALIDATE_PHP_BUILTIN: true
VALIDATE_DOCKERFILE_HADOLINT: true
VALIDATE_YAML: true
VALIDATE_JSON: true
VALIDATE_MARKDOWN: true

# Disable Composer validation to avoid PHP extension issues
VALIDATE_COMPOSER: false

# Disable other PHP linters that might cause issues
VALIDATE_PHP_PHPCS: false
VALIDATE_PHP_PHPSTAN: false
VALIDATE_PHP_PSALM: false

# Ignore vendor directory and other files we don't want to lint
IGNORE_GITIGNORED_FILES: true

# File patterns to ignore
IGNORE_PATTERNS:
  - "vendor/**"
  - "var/**"
  - "node_modules/**"
  - "*.min.js"
  - "*.min.css"
